name: go
on: [push]
jobs:
  build:
    name: Build (${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.18"]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3

      - run: go build .